version: '2'

volumes:
  cassandra_data:
    driver: local
  datomic_data:
    driver: local
  datomic_log:
    driver: local
  redis_data:
    driver: local

services:

  redis:
    image: redis:3.2.4-alpine
    volumes:
      - "redis_data:/data"
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra:3.10
    volumes:
      - "cassandra_data:/var/lib/cassandra"
    ports:
      - "9042:9042"
    mem_limit: 1024M

  datomic:
    build:
      context: .
      dockerfile: docker/images/datomic-transactor/Dockerfile
      args:
        DATOMIC_LOGIN: "$DATOMIC_LOGIN"
        DATOMIC_PASSWORD: "$DATOMIC_PASSWORD"
    environment:
      DB_NAME: "vimsical"
      DATOMIC_LICENSE_KEY: "$DATOMIC_LICENSE_KEY"
    volumes:
      - "datomic_data:/var/datomic/data"
      - "datomic_log:/var/datomic/log"
      - "./docker/images/datomic-transactor/config/dev/:/var/datomic/config/"
    ports:
      - "4334:4334"
      - "4335:4335"
      - "4336:4336"

  console:
    build:
      context: .
      dockerfile: docker/images/datomic-console/Dockerfile
      args:
        DATOMIC_LOGIN: "$DATOMIC_LOGIN"
        DATOMIC_PASSWORD: "$DATOMIC_PASSWORD"
    links:
      - datomic
    command: ["dev", "datomic:dev://datomic:4334"]
    ports:
      - "9000:9000"
