version: '2'

services:
  # Use transactor's test config
  #
  datomic:
    volumes:
      - "./docker/images/datomic-transactor/config/test/:/var/datomic/config/"

  # Application service
  #
  app:
    build:
      context: ..
      dockerfile: docker/images/backend/Dockerfile
      args:
        DATOMIC_LOGIN: "${DATOMIC_LOGIN}"
        DATOMIC_PASSWORD: "${DATOMIC_PASSWORD}"
    volumes:
      - "..:/usr/local/src/app"
    links:
      - cassandra
      - datomic
      - redis
