(ns vimsical.vcs.editor
  (:require
   ;; [vimsical.vcs.edit-event :as edit-event]
   ;; [vimsical.vcs.delta :as delta]
   [clojure.spec.alpha :as s]))


(s/def ::uuid-fn      ifn?)
(s/def ::pad-fn       ifn?)
(s/def ::timestamp-fn ifn?)

;; These fspecs trigger errors at runtime because the implementations work by
;; side-effects and the extra invocations generated by st/instrument cause
;; unexpected states

;; (s/def ::uuid-fn      (s/fspec :args (s/cat :edit-event ::edit-event/edit-event) :ret ::delta/uid))
;; (s/def ::pad-fn       (s/fspec :args (s/cat :edit-event ::edit-event/edit-event) :ret ::delta/pad))
;; (s/def ::timestamp-fn (s/fspec :args (s/cat :edit-event ::edit-event/edit-event) :ret ::delta/timestamp))

(s/def ::effects (s/keys :req [::uuid-fn ::pad-fn ::timestamp-fn]))
